"""Remove file_path column from crawlers table

Revision ID: 004_remove_file_path_column
Revises: 003_add_user_model
Create Date: 2026-04-05 22:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_remove_file_path_column'
down_revision: Union[str, None] = '003_add_user_model'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawlers', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawlers', sa.Column('file_path', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
