"""Add project model and relationship to crawlers

Revision ID: 005_add_project_model
Revises: 004_remove_file_path_column
Create Date: 2026-04-05 23:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '005_add_project_model'
down_revision: Union[str, None] = '004_remove_file_path_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create projects table (skip if already exists)
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'projects' not in inspector.get_table_names():
        op.create_table(
            'projects',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=200), nullable=False),
            sa.Column('description', sa.String(length=1000), nullable=True),
            sa.Column('working_directory', sa.String(length=500), nullable=False),
            sa.Column('python_executable', sa.String(length=500), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
        op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)

    # Add project_id column to crawlers table and create foreign key using batch mode for SQLite
    crawlers_columns = [col['name'] for col in inspector.get_columns('crawlers')]
    if 'project_id' not in crawlers_columns:
        # Use batch mode for SQLite to add column and foreign key
        with op.batch_alter_table('crawlers') as batch_op:
            batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(
                'fk_crawlers_project_id_projects',
                'projects', ['project_id'], ['id']
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key constraint and project_id column using batch mode for SQLite
    with op.batch_alter_table('crawlers') as batch_op:
        batch_op.drop_constraint('fk_crawlers_project_id_projects', type_='foreignkey')
        batch_op.drop_column('project_id')

    # Drop projects table
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')

    # ### end Alembic commands ###
