"""Remove working_directory and python_executable from crawlers table

These fields should be obtained from the associated project instead.

Revision ID: 006_remove_crawler_config_fields
Revises: 005_add_project_model
Create Date: 2026-04-05 23:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '006_remove_crawler_config_fields'
down_revision: Union[str, None] = '005_add_project_model'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove working_directory and python_executable columns from crawlers table using batch mode for SQLite
    with op.batch_alter_table('crawlers') as batch_op:
        # Check if columns exist before dropping
        conn = op.get_bind()
        inspector = inspect(conn)
        crawlers_columns = [col['name'] for col in inspector.get_columns('crawlers')]

        if 'working_directory' in crawlers_columns:
            batch_op.drop_column('working_directory')
        if 'python_executable' in crawlers_columns:
            batch_op.drop_column('python_executable')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add back working_directory and python_executable columns using batch mode for SQLite
    with op.batch_alter_table('crawlers') as batch_op:
        batch_op.add_column(sa.Column('working_directory', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('python_executable', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###
